# Generated by Django 5.0.4 on 2024-12-26 11:43

import services.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Counseling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, default='Tehran', max_length=30, null=True, verbose_name='City')),
                ('counseling_type', models.CharField(choices=[('ip', 'In Person'), ('op', 'On Phone'), ('oc', 'On Chat')], default='oc', max_length=30, verbose_name='Counseling Type')),
                ('date', models.CharField(choices=services.models.next_seven_days_shamsi, max_length=200, verbose_name='Date of Counseling')),
                ('time', models.CharField(choices=[('mg', 'Morning'), ('nn', 'Noon'), ('eg', 'Evening'), ('nt', 'Night')], max_length=200, verbose_name='Time of Counseling')),
                ('name_and_family', models.CharField(max_length=200, verbose_name='Name and Family')),
                ('phone_number', models.CharField(blank=True, max_length=11, null=True, verbose_name='Phone Number')),
                ('datetime_created', models.DateTimeField(auto_now_add=True, verbose_name='Date and Time of Creation')),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(choices=[('teh', 'Tehran'), ('krj', 'Karaj')], default='Tehran', max_length=30, verbose_name='City')),
                ('district', models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='District')),
                ('customer_type', models.CharField(choices=[('ol', 'Owner / Lessor'), ('bt', 'Buyer / Tenant')], max_length=30, verbose_name='Customer Type')),
                ('date', models.CharField(choices=services.models.next_seven_days_shamsi, max_length=200, verbose_name='Date of Session')),
                ('time', models.CharField(choices=[('mg', 'Morning'), ('nn', 'Noon'), ('eg', 'Evening'), ('nt', 'Night')], max_length=200, verbose_name='Time of Session')),
                ('name_and_family', models.CharField(max_length=200, verbose_name='Name and Family')),
                ('phone_number', models.CharField(blank=True, max_length=11, null=True, verbose_name='Phone Number')),
                ('datetime_created', models.DateTimeField(auto_now_add=True, verbose_name='Date and Time of Creation')),
            ],
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(choices=[('teh', 'Tehran'), ('krj', 'Karaj')], default='Tehran', max_length=30, verbose_name='City')),
                ('district', models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='District')),
                ('date', models.CharField(choices=services.models.next_seven_days_shamsi, max_length=200, verbose_name='Date of Visit')),
                ('time', models.CharField(choices=[('mg', 'Morning'), ('nn', 'Noon'), ('eg', 'Evening'), ('nt', 'Night')], max_length=200, verbose_name='Time of Visit')),
                ('name_and_family', models.CharField(max_length=200, verbose_name='Name and Family')),
                ('phone_number', models.CharField(blank=True, max_length=11, null=True, verbose_name='Phone Number')),
                ('datetime_created', models.DateTimeField(auto_now_add=True, verbose_name='Date and Time of Creation')),
            ],
        ),
    ]
