# Generated by Django 5.0.4 on 2025-02-22 18:11

import django.db.models.deletion
import services.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Counseling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, default='Tehran', max_length=30, null=True, verbose_name='شهر')),
                ('counseling_type', models.CharField(choices=[('ip', 'حضوری'), ('op', 'تلفنی'), ('oc', 'چتی')], default='oc', max_length=30, verbose_name='نوع مشاوره')),
                ('date', models.CharField(choices=services.models.next_seven_days_shamsi, max_length=200, verbose_name='تاریخ مشاوره')),
                ('time', models.CharField(choices=[('mg', 'صبح'), ('nn', 'ظهر'), ('eg', 'عصر'), ('nt', 'شب')], max_length=200, verbose_name='زمان مشاوره')),
                ('name_and_family', models.CharField(max_length=200, verbose_name='نام و نام خانوادگی')),
                ('phone_number', models.CharField(blank=True, max_length=11, null=True, verbose_name='تلفن همراه')),
                ('datetime_created', models.DateTimeField(auto_now_add=True, verbose_name='زمان و تاریخ ایجاد')),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price_session', models.PositiveBigIntegerField(verbose_name='Session Price')),
                ('price_visit', models.PositiveBigIntegerField(verbose_name='Visit Price')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='services.city')),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='services.province'),
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_type', models.CharField(choices=[('ol', 'مالک / موجر'), ('bt', 'خریدار / مستاجر')], max_length=30, verbose_name='نوع مشتری')),
                ('date', models.CharField(choices=services.models.next_seven_days_shamsi, max_length=200, verbose_name='تاریخ جلسه')),
                ('time', models.CharField(choices=[('mg', 'صبح'), ('nn', 'ظهر'), ('eg', 'عصر'), ('nt', 'شب')], max_length=200, verbose_name='زمان جلسه')),
                ('name_and_family', models.CharField(max_length=200, verbose_name='نام و نام خانوادگی')),
                ('phone_number', models.CharField(blank=True, max_length=11, null=True, verbose_name='تلفن همراه')),
                ('datetime_created', models.DateTimeField(auto_now_add=True, verbose_name='زمان و تاریخ ایجاد')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='services.city', verbose_name='شهر')),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='services.district', verbose_name='محله')),
                ('province', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='services.province', verbose_name='استان')),
            ],
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(choices=services.models.next_seven_days_shamsi, max_length=200, verbose_name='تاریخ بازدید')),
                ('time', models.CharField(choices=[('mg', 'صبح'), ('nn', 'ظهر'), ('eg', 'عصر'), ('nt', 'شب')], max_length=200, verbose_name='زمان بازدید')),
                ('name_and_family', models.CharField(max_length=200, verbose_name='نام و نام خانوادگی')),
                ('phone_number', models.CharField(blank=True, max_length=11, null=True, verbose_name='تلفن همراه')),
                ('datetime_created', models.DateTimeField(auto_now_add=True, verbose_name='زمان و تاریخ ایجاد')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visits', to='services.city', verbose_name='شهر')),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visits', to='services.district', verbose_name='محله')),
                ('province', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visits', to='services.province', verbose_name='استان')),
            ],
        ),
    ]
