# Generated by Django 5.0.4 on 2025-02-27 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='district',
            name='price_session',
        ),
        migrations.RemoveField(
            model_name='district',
            name='price_visit',
        ),
        migrations.AddField(
            model_name='district',
            name='price_session_rent',
            field=models.PositiveBigIntegerField(blank=True, default=1, null=True, verbose_name='Rent Session Price'),
        ),
        migrations.AddField(
            model_name='district',
            name='price_session_sale',
            field=models.PositiveBigIntegerField(blank=True, default=1, null=True, verbose_name='Sale Session Price'),
        ),
        migrations.AddField(
            model_name='district',
            name='price_visit_rent',
            field=models.PositiveBigIntegerField(blank=True, default=1, null=True, verbose_name='Rent Visit Price'),
        ),
        migrations.AddField(
            model_name='district',
            name='price_visit_sale',
            field=models.PositiveBigIntegerField(blank=True, default=1, null=True, verbose_name='Sale Visit Price'),
        ),
    ]
