# Generated by Django 5.0.4 on 2025-02-27 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_remove_district_price_session_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='district',
            name='price_visit_rent',
        ),
        migrations.RemoveField(
            model_name='district',
            name='price_visit_sale',
        ),
        migrations.AddField(
            model_name='district',
            name='price_visit',
            field=models.PositiveBigIntegerField(blank=True, default=1, null=True, verbose_name='Visit Price'),
        ),
        migrations.AlterField(
            model_name='counseling',
            name='city',
            field=models.CharField(blank=True, default='تهران', max_length=30, null=True, verbose_name='شهر'),
        ),
        migrations.AlterField(
            model_name='district',
            name='price_session_rent',
            field=models.PositiveBigIntegerField(blank=True, default=1, null=True, verbose_name='قیمت جلسه اجاره'),
        ),
        migrations.AlterField(
            model_name='district',
            name='price_session_sale',
            field=models.PositiveBigIntegerField(blank=True, default=1, null=True, verbose_name='قیمت جلسه خرید و فروش'),
        ),
    ]
