# Generated by Django 5.0.4 on 2025-02-28 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_alter_district_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='province',
            field=models.ForeignKey(blank=True, default='تهران', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='services.province', verbose_name='استان'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='province',
            field=models.ForeignKey(blank=True, default='تهران', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visits', to='services.province', verbose_name='استان'),
        ),
    ]
