# Generated by Django 5.0.4 on 2025-03-14 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_alter_session_province_alter_visit_province'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='trade_type',
            field=models.CharField(blank=True, choices=[('rt', 'Rent Trade'), ('st', 'Sale Trade')], max_length=30, null=True, verbose_name='Trade Type'),
        ),
    ]
