# Generated by Django 5.0.4 on 2025-06-04 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_session_trade_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': 'شهر', 'verbose_name_plural': 'شهرها'},
        ),
        migrations.AlterModelOptions(
            name='district',
            options={'verbose_name': 'محله (منطقه)', 'verbose_name_plural': 'محلات (مناطق)'},
        ),
        migrations.AlterModelOptions(
            name='province',
            options={'verbose_name': 'استان', 'verbose_name_plural': 'استان\u200cها'},
        ),
        migrations.AlterField(
            model_name='counseling',
            name='date',
            field=models.CharField(max_length=200, verbose_name='تاریخ مشاوره'),
        ),
        migrations.AlterField(
            model_name='district',
            name='price_session_rent',
            field=models.PositiveBigIntegerField(blank=True, default=1, null=True, verbose_name='قیمت جلسه رهن و اجاره'),
        ),
        migrations.AlterField(
            model_name='district',
            name='price_visit',
            field=models.PositiveBigIntegerField(blank=True, default=1, null=True, verbose_name='قیمت بازدید'),
        ),
        migrations.AlterField(
            model_name='session',
            name='date',
            field=models.CharField(max_length=200, verbose_name='تاریخ جلسه'),
        ),
        migrations.AlterField(
            model_name='session',
            name='trade_type',
            field=models.CharField(blank=True, choices=[('rt', 'رهن و اجاره'), ('st', 'خرید و فروش')], max_length=30, null=True, verbose_name='نوع معامله'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='date',
            field=models.CharField(max_length=200, verbose_name='تاریخ بازدید'),
        ),
    ]
