# Generated by Django 5.0.4 on 2025-06-05 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_alter_city_options_alter_district_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='counseling',
            options={'verbose_name': 'مشاوره', 'verbose_name_plural': 'مشاوره\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='session',
            options={'verbose_name': 'نشست', 'verbose_name_plural': 'نشست\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='visit',
            options={'verbose_name': 'بازدید', 'verbose_name_plural': 'بازدیدها'},
        ),
        migrations.RemoveField(
            model_name='district',
            name='price_visit',
        ),
        migrations.AddField(
            model_name='district',
            name='price_visit_rent',
            field=models.PositiveBigIntegerField(blank=True, default=1, null=True, verbose_name='Rent Visit Price'),
        ),
        migrations.AddField(
            model_name='district',
            name='price_visit_sale',
            field=models.PositiveBigIntegerField(blank=True, default=1, null=True, verbose_name='Sale Visit Price'),
        ),
        migrations.AlterField(
            model_name='district',
            name='name',
            field=models.CharField(max_length=5),
        ),
    ]
