# Generated by Django 5.0.4 on 2025-06-05 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_alter_counseling_options_alter_session_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='price_session_rent',
            field=models.PositiveBigIntegerField(blank=True, null=True, verbose_name='قیمت جلسه رهن و اجاره'),
        ),
        migrations.AlterField(
            model_name='district',
            name='price_session_sale',
            field=models.PositiveBigIntegerField(blank=True, null=True, verbose_name='قیمت جلسه خرید و فروش'),
        ),
        migrations.AlterField(
            model_name='district',
            name='price_visit_rent',
            field=models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Rent Visit Price'),
        ),
        migrations.AlterField(
            model_name='district',
            name='price_visit_sale',
            field=models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Sale Visit Price'),
        ),
    ]
