# Generated by Django 5.0.4 on 2025-06-05 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_alter_district_price_session_rent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='trade_type',
            field=models.CharField(blank=True, choices=[('rt', 'رهن و اجاره'), ('st', 'خرید و فروش')], max_length=30, null=True, verbose_name='نوع معامله'),
        ),
    ]
