# Generated by Django 5.0.4 on 2025-06-05 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0011_counseling_code_session_code_visit_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='datetime_created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='زمان و تاریخ ایجاد'),
        ),
        migrations.AddField(
            model_name='district',
            name='datetime_created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='زمان و تاریخ ایجاد'),
        ),
        migrations.AddField(
            model_name='province',
            name='datetime_created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='زمان و تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='counseling',
            name='city',
            field=models.CharField(blank=True, choices=[('teh', 'تهران')], max_length=30, null=True, verbose_name='شهر'),
        ),
    ]
