# Generated by Django 5.0.4 on 2025-06-05 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0012_city_datetime_created_district_datetime_created_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='district',
            options={'ordering': ['ordering'], 'verbose_name': 'محله (منطقه)', 'verbose_name_plural': 'محلات (مناطق)'},
        ),
        migrations.AddField(
            model_name='district',
            name='human_name',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Humanized Name'),
        ),
        migrations.AddField(
            model_name='district',
            name='ordering',
            field=models.IntegerField(blank=True, null=True, verbose_name='Ordering'),
        ),
    ]
