# Generated by Django 5.0.4 on 2025-06-05 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0013_alter_district_options_district_human_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='district',
            old_name='human_name',
            new_name='humanized_name',
        ),
    ]
