# Generated by Django 5.0.4 on 2025-06-05 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0014_rename_human_name_district_humanized_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='district',
            options={'ordering': ['datetime_created'], 'verbose_name': 'محله (منطقه)', 'verbose_name_plural': 'محلات (مناطق)'},
        ),
        migrations.RemoveField(
            model_name='district',
            name='humanized_name',
        ),
        migrations.RemoveField(
            model_name='district',
            name='ordering',
        ),
        migrations.AddField(
            model_name='district',
            name='name_code',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='district',
            name='name',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Humanized Name'),
        ),
    ]
