# Generated by Django 5.0.4 on 2025-06-05 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0015_alter_district_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='district',
            options={'ordering': ['name_code'], 'verbose_name': 'محله (منطقه)', 'verbose_name_plural': 'محلات (مناطق)'},
        ),
        migrations.AddField(
            model_name='visit',
            name='customer_type',
            field=models.CharField(blank=True, choices=[('ol', 'مالک / موجر'), ('bt', 'خریدار / مستاجر')], max_length=10, null=True, verbose_name='نوع مشتری'),
        ),
        migrations.AlterField(
            model_name='session',
            name='customer_type',
            field=models.CharField(choices=[('ol', 'مالک / موجر'), ('bt', 'خریدار / مستاجر')], max_length=10, verbose_name='نوع مشتری'),
        ),
        migrations.AlterField(
            model_name='session',
            name='trade_type',
            field=models.CharField(blank=True, choices=[('rt', 'رهن و اجاره'), ('st', 'خرید و فروش')], max_length=10, null=True, verbose_name='نوع معامله'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='trade_type',
            field=models.CharField(blank=True, choices=[('rt', 'رهن و اجاره'), ('st', 'خرید و فروش')], max_length=10, null=True, verbose_name='نوع معامله'),
        ),
    ]
