# Generated by Django 5.0.4 on 2025-06-05 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0016_alter_district_options_visit_customer_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visit',
            name='customer_type',
        ),
    ]
