# Generated by Django 5.0.4 on 2025-06-04 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': 'شهر', 'verbose_name_plural': 'شهرها'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'پروفایل', 'verbose_name_plural': 'پروفایل\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='province',
            options={'verbose_name': 'استان', 'verbose_name_plural': 'استان\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ('-datetime_created',), 'verbose_name': 'وظیفه', 'verbose_name_plural': 'وظایف'},
        ),
        migrations.AlterField(
            model_name='task',
            name='code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
