# Generated by Django 5.0.4 on 2025-06-05 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_city_options_alter_profile_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusermodel',
            name='is_verified',
            field=models.CharField(blank=True, choices=[('a', 'تایید شده'), ('n', 'تایید نشده'), ('i', 'در حال بررسی')], default='n', max_length=10, null=True, verbose_name='وضعیت تایید حساب کاربری'),
        ),
        migrations.AlterField(
            model_name='task',
            name='type',
            field=models.CharField(blank=True, choices=[('cns', 'مشاوره'), ('ses', 'نشست'), ('vis', 'بازدید')], max_length=6, null=True, verbose_name='نوع موقعیت کاری'),
        ),
    ]
