# Generated by Django 5.0.4 on 2025-02-22 18:11

import django.db.models.deletion
import django_quill.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان دسته\u200cبندی')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=250, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover', models.ImageField(upload_to='blogs/covers/', verbose_name='کاور مقاله')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان مقاله')),
                ('body', django_quill.fields.QuillField(verbose_name='متن مقاله')),
                ('date_creation', models.DateField(auto_now_add=True, verbose_name='تاریخ و زمان ایجاد')),
                ('date_modification', models.DateField(auto_now=True, verbose_name='تاریخ و زمان اصلاح')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=250, null=True, unique=True)),
                ('status', models.CharField(choices=[('pub', 'Published'), ('drf', 'Draft')], max_length=3, verbose_name='وضعیت مقاله')),
                ('blog_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='blog_category', to='blog.blogcategory', verbose_name='دسته\u200cبندی مقاله')),
            ],
            options={
                'ordering': ('-date_creation',),
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='نگارنده پیام')),
                ('body', models.CharField(max_length=500, verbose_name='متن پیام')),
                ('status', models.CharField(blank=True, choices=[('acc', 'تایید شده'), ('rej', 'رد شده'), ('wit', 'در حال بررسی')], default='wit', max_length=30, null=True, verbose_name='وضعیت')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.blog')),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply_name', models.CharField(max_length=40, verbose_name='نگارنده پاسخ')),
                ('body', models.CharField(max_length=500, verbose_name='متن پاسخ')),
                ('status', models.CharField(blank=True, choices=[('acc', 'تایید شده'), ('rej', 'رد شده'), ('wit', 'در حال بررسی')], default='wit', max_length=30, null=True, verbose_name='وضعیت')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('blog', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blog_replies', to='blog.blog')),
                ('parent_comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='blog.comment')),
                ('parent_reply', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies_pr', to='blog.reply')),
            ],
            options={
                'ordering': ['date_creation'],
            },
        ),
    ]
