# Generated by Django 5.0.4 on 2025-06-04 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ('-date_creation',), 'verbose_name': 'مقاله', 'verbose_name_plural': 'مقالات'},
        ),
        migrations.AlterModelOptions(
            name='blogcategory',
            options={'verbose_name': 'دسته\u200cبندی', 'verbose_name_plural': 'دسته\u200cبندی مقالات'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-date_creation'], 'verbose_name': 'نظر', 'verbose_name_plural': 'نظرات'},
        ),
        migrations.AlterModelOptions(
            name='reply',
            options={'ordering': ['date_creation'], 'verbose_name': 'پاسخ', 'verbose_name_plural': 'پاسخ\u200cها'},
        ),
    ]
