# Generated by Django 5.0.4 on 2025-06-05 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blog_options_alter_blogcategory_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='cover',
            field=models.ImageField(upload_to='blogs/covers/', verbose_name='تصویر مقاله'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='status',
            field=models.CharField(choices=[('pub', 'انتشار یافته'), ('drf', 'پیش\u200cنویس')], max_length=3, verbose_name='وضعیت مقاله'),
        ),
    ]
